// Generated by CoffeeScript 1.6.2
var BlessCompiler, bless;

bless = require('bless');

module.exports = BlessCompiler = (function() {
  BlessCompiler.prototype.brunchPlugin = true;

  BlessCompiler.prototype.type = 'stylesheet';

  function BlessCompiler(config) {
    var _ref, _ref1, _ref2;

    this.config = config;
    this.options = (_ref = (_ref1 = this.config) != null ? (_ref2 = _ref1.plugins) != null ? _ref2.bless : void 0 : void 0) != null ? _ref : {};
  }

  BlessCompiler.prototype.minify = function(data, path, callback) {
    var err, error, optimized;

    try {
      optimized = bless.process(data, this.options);
    } catch (_error) {
      err = _error;
      error = "Bless failed on " + path + ": " + error;
    }
    return process.nextTick(function() {
      return callback(error, optimized || data);
    });
  };

  return BlessCompiler;

})();
